train:
    folder: 'top'
    num_images: 3
    device: 'cuda'
    parallel: False
    batch_size: 16
    num_workers: 8
    epochs: 30
    

optimizer:
    lr: 0.005
    momentum: 0.9
    scheduler_steps: 10
    gamma: 0.5

log:
    chkpt_dir: 'chkpt'

